### ISSUE TITLE
Datepicker of Umbraco does not work anymore

### ISSUE THREAD

**Issue by JeffreyPerplex** [RobbieLD/FontAwesomeIconFinder#6]
If you install your package the default Datepicker of Umbraco is not working anymore.

![afbeelding](https://github.com/RobbieLD/FontAwesomeIconFinder/assets/12457148/986b34d7-3fa2-4f75-9b9f-eb80d5d62d9e)

This is because you overwrite the default built-in Node-definition in your files I guess.

the javascript that does not work is (if selector instanceOf Node)... Because you replace your Node with your own implementation (https://github.com/RobbieLD/FontAwesomeIconFinder/blob/master/src/fontawesomeiconfinder.node.js). Easiest fix is to rename your "Node" to something like "FontAwesomeNode". 

Please note: With the uMarketingSuite we are reusing Umbraco's implementation of the datepicker. Our package is now not working correctly either. That's the reason we hope you get this fixed.

**Comment by PerplexDaniel** [comment]
I looked together with Jeffrey at this, I'll add a little more information.

The [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node) class is a native built-in class, every browser ships with it. If you run `Node` in the Chrome console of any page (such as this GitHub page) you will see this output:

![image](https://github.com/RobbieLD/FontAwesomeIconFinder/assets/24297947/904b0231-1dd6-47f8-b38e-90d057fe5297)

However, your package overwrites the global built-in Node class with your own implementation. As such, the built-in `Node` class will no longer exist, and typing `Node` in the console of an Umbraco backoffice that has this package installed will instead show your override implementation.

![image](https://github.com/RobbieLD/FontAwesomeIconFinder/assets/24297947/87cf3a90-dde6-4183-9aa7-0bdcdfddb4f3)

Umbraco uses flatpickr for their datepicker, and it turns out they use [`selector instanceof Node`](https://github.com/flatpickr/flatpickr/blob/v4.6.9/src/index.ts#L2915) in their code. 
Because `Node` is no longer the assumed built-in class but instead your custom class, this check will return `false` in cases where it should actually return `true`. As a result, Umbraco's DatePicker no longer renders correctly.

As Jeffrey suggested an easy fix is to rename your class to something else that is not a reserved name.

**Comment by RobbieLD** [comment]
Thanks for looking into this guys, I really appreciate it. It's been a while since I worked on the code for this but I'll take a look at your suggestion and get an update pushed as soon.

**Comment by RobbieLD** [comment]
Hi @PerplexDaniel  and @JeffreyPerplex, I've published and updated (version 1.1.2) which should fix this. I've changed the name of the node class to be FaifNode. Thanks for the working you did in figuring this out. Let me know if it's working and I'll close the issue.

**Comment by PerplexDaniel** [comment]
@RobbieLD Great, thank you for the quick turnaround. I just installed 1.1.2 and this has resolved the issue 🥳!

**Comment by JeffreyPerplex** [comment]
Whoop whoop! Thanks @RobbieLD
